name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: |
          export NODE_ENV=production
          npm run build

      - name: List build output
        run: |
          echo "=== Build Output ==="
          ls -la out/
          echo "=== CSS Files ==="
          ls -la out/_next/static/css/
          echo "=== JS Files ==="
          ls -la out/_next/static/chunks/

      - name: Deploy
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout --orphan gh-pages
          git rm -rf .
          echo "=== Copying files ==="
          # Copy only the build output, not node_modules
          cp -r out/* .
          # Remove any node_modules if accidentally copied
          rm -rf node_modules
          rm -rf .git
          echo "=== Files after copy ==="
          ls -la
          echo "=== CSS files after copy ==="
          ls -la _next/static/css/ || echo "CSS folder not found"
          # Only add specific files, not everything
          git add _next/
          git add *.html
          git add *.js
          git add *.css
          git add favicon.ico
          git add *.svg
          git status
          git commit -m "Deploy to GitHub Pages - $(date)"
          git push origin gh-pages --force
